services:
  mongodb:
    image: mongo:8.0.5
    container_name: mailmongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    
  api:
    build: .
    container_name: mailapi
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/emails